export const LEVEL_REWARDS = [
  { level: 1,  diamonds: 5,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 2,  diamonds: 0,   shards: 200,  ether: 0,    boxes: [],                                        cores: [] },
  { level: 3,  diamonds: 5,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 4,  diamonds: 0,   shards: 0,    ether: 200,  boxes: [],                                        cores: [] },
  { level: 5,  diamonds: 0,   shards: 0,    ether: 0,    boxes: ['rare','rare','rare'],                       cores: [] },
  { level: 6,  diamonds: 5,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 7,  diamonds: 0,   shards: 300,  ether: 0,    boxes: [],                                        cores: [] },
  { level: 8,  diamonds: 5,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 9,  diamonds: 0,   shards: 0,    ether: 300,  boxes: [],                                        cores: [] },
  { level: 10, diamonds: 15,  shards: 0,    ether: 0,    boxes: ['rare','rare'],                            cores: [] },
  { level: 11, diamonds: 5,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 12, diamonds: 0,   shards: 400,  ether: 0,    boxes: [],                                        cores: [] },
  { level: 13, diamonds: 0,   shards: 0,    ether: 0,    boxes: [],                                        cores: [{ level: 0 }] },
  { level: 14, diamonds: 0,   shards: 0,    ether: 400,  boxes: [],                                        cores: [] },
  { level: 15, diamonds: 0,   shards: 0,    ether: 0,    boxes: ['rare','rare'],                            cores: [] },
  { level: 16, diamonds: 5,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 17, diamonds: 0,   shards: 500,  ether: 0,    boxes: [],                                        cores: [] },
  { level: 18, diamonds: 5,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 19, diamonds: 0,   shards: 0,    ether: 500,  boxes: [],                                        cores: [] },
  { level: 20, diamonds: 20,  shards: 0,    ether: 0,    boxes: ['rare','rare'],                            cores: [] },
  { level: 21, diamonds: 5,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 22, diamonds: 0,   shards: 500,  ether: 0,    boxes: [],                                        cores: [] },
  { level: 23, diamonds: 0,   shards: 0,    ether: 0,    boxes: [],                                        cores: [{ level: 0 }] },
  { level: 24, diamonds: 0,   shards: 0,    ether: 500,  boxes: [],                                        cores: [] },
  { level: 25, diamonds: 30,  shards: 0,    ether: 0,    boxes: ['rare','rare','rare'],                     cores: [] },
  { level: 26, diamonds: 5,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 27, diamonds: 0,   shards: 500,  ether: 0,    boxes: [],                                        cores: [] },
  { level: 28, diamonds: 5,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 29, diamonds: 0,   shards: 0,    ether: 500,  boxes: [],                                        cores: [] },
  { level: 30, diamonds: 25,  shards: 0,    ether: 0,    boxes: ['epic'],                                   cores: [] },
  { level: 31, diamonds: 5,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 32, diamonds: 0,   shards: 600,  ether: 0,    boxes: [],                                        cores: [] },
  { level: 33, diamonds: 0,   shards: 0,    ether: 0,    boxes: [],                                        cores: [{ level: 0 }] },
  { level: 34, diamonds: 0,   shards: 0,    ether: 600,  boxes: [],                                        cores: [] },
  { level: 35, diamonds: 0,   shards: 0,    ether: 0,    boxes: ['rare','rare'],                            cores: [] },
  { level: 36, diamonds: 5,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 37, diamonds: 0,   shards: 600,  ether: 0,    boxes: [],                                        cores: [] },
  { level: 38, diamonds: 0,   shards: 0,    ether: 0,    boxes: [],                                        cores: [{ level: 0 }] },
  { level: 39, diamonds: 0,   shards: 0,    ether: 600,  boxes: [],                                        cores: [] },
  { level: 40, diamonds: 30,  shards: 0,    ether: 0,    boxes: ['epic'],                                   cores: [] },
  { level: 41, diamonds: 8,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 42, diamonds: 0,   shards: 700,  ether: 0,    boxes: [],                                        cores: [] },
  { level: 43, diamonds: 0,   shards: 0,    ether: 0,    boxes: [],                                        cores: [{ level: 0 }] },
  { level: 44, diamonds: 0,   shards: 0,    ether: 700,  boxes: [],                                        cores: [] },
  { level: 45, diamonds: 0,   shards: 0,    ether: 0,    boxes: ['rare','rare','rare'],                     cores: [] },
  { level: 46, diamonds: 8,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 47, diamonds: 0,   shards: 700,  ether: 0,    boxes: [],                                        cores: [] },
  { level: 48, diamonds: 0,   shards: 0,    ether: 0,    boxes: [],                                        cores: [{ level: 0 }] },
  { level: 49, diamonds: 0,   shards: 0,    ether: 700,  boxes: [],                                        cores: [] },
  { level: 50, diamonds: 250, shards: 0,    ether: 0,    boxes: ['epic','epic'],                             cores: [{ level: 0 }] },
  { level: 51, diamonds: 8,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 52, diamonds: 0,   shards: 800,  ether: 0,    boxes: [],                                        cores: [] },
  { level: 53, diamonds: 0,   shards: 0,    ether: 0,    boxes: [],                                        cores: [{ level: 0 }] },
  { level: 54, diamonds: 0,   shards: 0,    ether: 800,  boxes: [],                                        cores: [] },
  { level: 55, diamonds: 0,   shards: 0,    ether: 0,    boxes: ['rare','rare'],                            cores: [] },
  { level: 56, diamonds: 8,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 57, diamonds: 0,   shards: 800,  ether: 0,    boxes: [],                                        cores: [] },
  { level: 58, diamonds: 0,   shards: 0,    ether: 0,    boxes: [],                                        cores: [{ level: 0 }] },
  { level: 59, diamonds: 0,   shards: 0,    ether: 800,  boxes: [],                                        cores: [] },
  { level: 60, diamonds: 40,  shards: 0,    ether: 0,    boxes: ['epic'],                                   cores: [] },
  { level: 61, diamonds: 8,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 62, diamonds: 0,   shards: 900,  ether: 0,    boxes: [],                                        cores: [] },
  { level: 63, diamonds: 0,   shards: 0,    ether: 0,    boxes: [],                                        cores: [{ level: 0 }] },
  { level: 64, diamonds: 0,   shards: 0,    ether: 900,  boxes: [],                                        cores: [] },
  { level: 65, diamonds: 0,   shards: 0,    ether: 0,    boxes: ['rare','rare','rare'],                     cores: [] },
  { level: 66, diamonds: 8,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 67, diamonds: 0,   shards: 900,  ether: 0,    boxes: [],                                        cores: [] },
  { level: 68, diamonds: 0,   shards: 0,    ether: 0,    boxes: [],                                        cores: [{ level: 0 }] },
  { level: 69, diamonds: 0,   shards: 0,    ether: 900,  boxes: [],                                        cores: [] },
  { level: 70, diamonds: 50,  shards: 0,    ether: 0,    boxes: ['epic','epic'],                             cores: [] },
  { level: 71, diamonds: 8,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 72, diamonds: 0,   shards: 1000, ether: 0,    boxes: [],                                        cores: [] },
  { level: 73, diamonds: 0,   shards: 0,    ether: 0,    boxes: [],                                        cores: [{ level: 0 }] },
  { level: 74, diamonds: 0,   shards: 0,    ether: 1000, boxes: [],                                        cores: [] },
  { level: 75, diamonds: 0,   shards: 0,    ether: 0,    boxes: ['mythic'],                                 cores: [] },
  { level: 76, diamonds: 8,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 77, diamonds: 0,   shards: 1000, ether: 0,    boxes: [],                                        cores: [] },
  { level: 78, diamonds: 0,   shards: 0,    ether: 0,    boxes: [],                                        cores: [{ level: 0 }] },
  { level: 79, diamonds: 0,   shards: 0,    ether: 1000, boxes: [],                                        cores: [] },
  { level: 80, diamonds: 60,  shards: 0,    ether: 0,    boxes: ['epic','epic'],                             cores: [] },
  { level: 81, diamonds: 8,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 82, diamonds: 0,   shards: 1000, ether: 0,    boxes: [],                                        cores: [] },
  { level: 83, diamonds: 0,   shards: 0,    ether: 0,    boxes: [],                                        cores: [{ level: 0 }] },
  { level: 84, diamonds: 0,   shards: 0,    ether: 1000, boxes: [],                                        cores: [] },
  { level: 85, diamonds: 0,   shards: 0,    ether: 0,    boxes: ['rare','rare','rare'],                     cores: [{ level: 0 }] },
  { level: 86, diamonds: 8,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 87, diamonds: 0,   shards: 1000, ether: 0,    boxes: [],                                        cores: [] },
  { level: 88, diamonds: 0,   shards: 0,    ether: 0,    boxes: [],                                        cores: [{ level: 0 }] },
  { level: 89, diamonds: 0,   shards: 0,    ether: 1000, boxes: [],                                        cores: [] },
  { level: 90, diamonds: 70,  shards: 0,    ether: 0,    boxes: ['mythic'],                                 cores: [] },
  { level: 91, diamonds: 8,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 92, diamonds: 0,   shards: 1000, ether: 0,    boxes: [],                                        cores: [] },
  { level: 93, diamonds: 0,   shards: 0,    ether: 0,    boxes: [],                                        cores: [{ level: 0 }] },
  { level: 94, diamonds: 0,   shards: 0,    ether: 1000, boxes: [],                                        cores: [] },
  { level: 95, diamonds: 0,   shards: 0,    ether: 0,    boxes: ['epic','epic'],                             cores: [] },
  { level: 96, diamonds: 8,   shards: 0,    ether: 0,    boxes: [],                                        cores: [] },
  { level: 97, diamonds: 0,   shards: 1000, ether: 0,    boxes: [],                                        cores: [] },
  { level: 98, diamonds: 0,   shards: 0,    ether: 0,    boxes: [],                                        cores: [{ level: 0 }] },
  { level: 99, diamonds: 0,   shards: 0,    ether: 1000, boxes: [],                                        cores: [] },
  { level: 100, diamonds: 500, shards: 1000, ether: 1000, boxes: ['mythic','mythic'],                       cores: [{ level: 5 }] },
];

export const LEVEL_REWARDS_MAP = new Map(LEVEL_REWARDS.map(r => [r.level, r]));
